sudo: false
language: node_js
node_js:
- '0.10'
cache:
  bundler: true
  directories:
  - node_modules
env:
  matrix:
  - NODE_ENV=test
branches:
  only:
  - master
deploy:
  provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: wJ4kJGhQDPcQnqJqn6v1yWU8FH6nllc/631cKjyHTXPJUvbjL1JYyQdAd54Dz7PGfrVdQzpAvpqjwiQg2ahAzrBvjYF+49ei6xtHzhsDyXn56dI9YyP0hTu4j7hMdSTIHayHUks4h/G7T+uU5dxr9SnsTOCXRwcpIs3aows3jVA=
  app-id: dc34c05f-6cd6-4b9d-b4b0-916e02035ba9
